global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Travel_Explorer.Domain.Entities;
global using Travel_Explorer.Domain.Interfaces;
global using Travel_Explorer.Domain.Common;
