# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - travel-explorer-prod-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: travelexplorerregistery.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_168BA83C13874E97B1DDF9FA458326A9 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_F1995D94276449FBBF54444C8F8F2595 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: travelexplorerregistery.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_168BA83C13874E97B1DDF9FA458326A9 }}/travel-explorer:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_520374A8A1DF46DD81EBF6EACFCF5B42 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_76A5136FC38E420898ABFC49AD2CC591 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_24DC5F03ECE44B9D9F6614ED90E2C65A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'travel-explorer-prod-api'
          slot-name: 'Production'
          images: 'travelexplorerregistery.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_168BA83C13874E97B1DDF9FA458326A9 }}/travel-explorer:${{ github.sha }}'
          