name: Build and deploy ASP.Net Core app to Azure Web App - Travel-Explorer

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore "./Travel Explorer/Travel Explorer.csproj"

      - name: Build project
        run: dotnet build "./Travel Explorer/Travel Explorer.csproj" --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish "./Travel Explorer/Travel Explorer.csproj" -c Release -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: publish

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: .

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5BA335CD50AC4CA3A7AF6C93CCFCEA16 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_383F45D970FA4FECA8920C6E2BBECEAB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9508D9180F134369A0FCCC8896C2F756 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Travel-Explorer'
          slot-name: 'Production'
          package: .
